# Generated by Django 5.1.1 on 2024-10-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'title')},
        ),
    ]
